PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS commands (
	id			INTEGER		NOT NULL PRIMARY KEY AUTOINCREMENT,
	"name"		TEXT		NOT NULL UNIQUE,
	created_at	TIMESTAMP	NOT NULL,
	updated_at	TIMESTAMP	NOT NULL
);

CREATE TABLE IF NOT EXISTS command_items (
	id			INTEGER		NOT NULL PRIMARY KEY AUTOINCREMENT,
	command_id  INTEGER		NOT NULL,
	script		TEXT		NOT NULL UNIQUE,
	created_at	TIMESTAMP	NOT NULL,
	updated_at	TIMESTAMP	NOT NULL,
	FOREIGN KEY (command_id) REFERENCES commands(id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS manuals (
	id			INTEGER		NOT NULL PRIMARY KEY AUTOINCREMENT,
	"name"		TEXT		NOT NULL UNIQUE,
	body		TEXT		NOT NULL,
	created_at	TIMESTAMP	NOT NULL,
	updated_at	TIMESTAMP	NOT NULL
);
